# Generated by Django 5.0.4 on 2024-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
