# Generated by Django 5.0.4 on 2024-04-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_remove_order_is_completed_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
