# Generated by Django 5.0.4 on 2024-04-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('target_year', models.PositiveIntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
