# Generated by Django 5.0.4 on 2024-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_targetorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetorder',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
