# Generated by Django 5.0.4 on 2024-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_alter_targetorder_target_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetorder',
            unique_together={('target_month', 'target_year')},
        ),
        migrations.CreateModel(
            name='TargetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('target_year', models.PositiveIntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
            options={
                'unique_together': {('target_month', 'target_year')},
            },
        ),
    ]
