# Generated by Django 5.0.4 on 2024-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_product_buying_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('buying_price__lte', models.F('price'))), name='buying_price_less_than_or_equal_to_price'),
        ),
    ]
