# Generated by Django 5.0.4 on 2024-04-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_product_buying_price_less_than_or_equal_to_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='buying_price_less_than_or_equal_to_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
