# Generated by Django 5.0.4 on 2024-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_remove_product_buying_price_less_than_or_equal_to_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
